# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import sys

if sys.version_info >= (3, 11):
    pass
else:
    pass

accessToken: str | None
"""
Machine Account Access Token (env: `BWS_ACCESS_TOKEN`)).
"""

clientId: str | None
"""
Client ID (env: `BW_CLIENTID`)
"""

clientSecret: str | None

email: str | None
"""
Login Email of the Vault (env: `BW_EMAIL`).
"""

experimentals: str | None
"""
Enable experimental features.
"""

extraCaCerts: str | None
"""
Extends the well known 'root' CAs (like VeriSign) with the extra certificates in file (env: `NODE_EXTRA_CA_CERTS`,
doesn't work with embedded client).
"""

masterPassword: str | None

server: str | None
"""
Bitwarden Server URL (default: `https://vault.bitwarden.com`, env: `BW_URL`).
"""

sessionKey: str | None
"""
A Bitwarden Session Key (env: `BW_SESSION`)
"""

vaultPath: str | None
"""
Alternative directory for storing the Vault locally (default: `.bitwarden/`, env: `BITWARDENCLI_APPDATA_DIR`; set to
empty string to use CLI default).
"""

