# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import sys

import pulumi
import pulumi.runtime

if sys.version_info >= (3, 11):
    pass
else:
    pass

__all__ = [
    'Experimentals',
]

@pulumi.output_type
class Experimentals(dict):
    def __init__(__self__, *,
                 disable_sync_after_write_verification: _builtins.bool | None = None,
                 embedded_client: _builtins.bool | None = None):
        """
        :param _builtins.bool disable_sync_after_write_verification: Skip verification of server-side modifications (like timestamp updates) after write operations - useful when the Bitwarden server makes minor, non-functional changes to objects.
        :param _builtins.bool embedded_client: Use the embedded client instead of an external binary.
        """
        if disable_sync_after_write_verification is not None:
            pulumi.set(__self__, "disable_sync_after_write_verification", disable_sync_after_write_verification)
        if embedded_client is not None:
            pulumi.set(__self__, "embedded_client", embedded_client)

    @_builtins.property
    @pulumi.getter(name="disableSyncAfterWriteVerification")
    def disable_sync_after_write_verification(self) -> _builtins.bool | None:
        """
        Skip verification of server-side modifications (like timestamp updates) after write operations - useful when the Bitwarden server makes minor, non-functional changes to objects.
        """
        return pulumi.get(self, "disable_sync_after_write_verification")

    @_builtins.property
    @pulumi.getter(name="embeddedClient")
    def embedded_client(self) -> _builtins.bool | None:
        """
        Use the embedded client instead of an external binary.
        """
        return pulumi.get(self, "embedded_client")


