# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import sys

import pulumi
import pulumi.runtime

if sys.version_info >= (3, 11):
    pass
else:
    pass

import types

__config__ = pulumi.Config('bitwarden')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def access_token(self) -> str | None:
        """
        Machine Account Access Token (env: `BWS_ACCESS_TOKEN`)).
        """
        return __config__.get('accessToken')

    @_builtins.property
    def client_id(self) -> str | None:
        """
        Client ID (env: `BW_CLIENTID`)
        """
        return __config__.get('clientId')

    @_builtins.property
    def client_secret(self) -> str | None:
        return __config__.get('clientSecret')

    @_builtins.property
    def email(self) -> str | None:
        """
        Login Email of the Vault (env: `BW_EMAIL`).
        """
        return __config__.get('email')

    @_builtins.property
    def experimentals(self) -> str | None:
        """
        Enable experimental features.
        """
        return __config__.get('experimentals')

    @_builtins.property
    def extra_ca_certs(self) -> str | None:
        """
        Extends the well known 'root' CAs (like VeriSign) with the extra certificates in file (env: `NODE_EXTRA_CA_CERTS`,
        doesn't work with embedded client).
        """
        return __config__.get('extraCaCerts')

    @_builtins.property
    def master_password(self) -> str | None:
        return __config__.get('masterPassword')

    @_builtins.property
    def server(self) -> str | None:
        """
        Bitwarden Server URL (default: `https://vault.bitwarden.com`, env: `BW_URL`).
        """
        return __config__.get('server')

    @_builtins.property
    def session_key(self) -> str | None:
        """
        A Bitwarden Session Key (env: `BW_SESSION`)
        """
        return __config__.get('sessionKey')

    @_builtins.property
    def vault_path(self) -> str | None:
        """
        Alternative directory for storing the Vault locally (default: `.bitwarden/`, env: `BITWARDENCLI_APPDATA_DIR`; set to
        empty string to use CLI default).
        """
        return __config__.get('vaultPath')

