# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import typing

from . import _utilities, outputs
from ._inputs import *

# Export this package's modules as members:
from .attachment import *
from .folder import *
from .get_attachment import *
from .get_folder import *
from .get_item_login import *
from .get_item_secure_note import *
from .get_item_ssh_key import *
from .get_org_collection import *
from .get_org_group import *
from .get_org_member import *
from .get_organization import *
from .get_project import *
from .get_secret import *
from .item_login import *
from .item_secure_note import *
from .item_ssh_key import *
from .org_collection import *
from .project import *
from .provider import *
from .secret import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_bitwarden.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_bitwarden.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "bitwarden",
  "mod": "index/attachment",
  "fqn": "pulumi_bitwarden",
  "classes": {
   "bitwarden:index/attachment:Attachment": "Attachment"
  }
 },
 {
  "pkg": "bitwarden",
  "mod": "index/folder",
  "fqn": "pulumi_bitwarden",
  "classes": {
   "bitwarden:index/folder:Folder": "Folder"
  }
 },
 {
  "pkg": "bitwarden",
  "mod": "index/itemLogin",
  "fqn": "pulumi_bitwarden",
  "classes": {
   "bitwarden:index/itemLogin:ItemLogin": "ItemLogin"
  }
 },
 {
  "pkg": "bitwarden",
  "mod": "index/itemSecureNote",
  "fqn": "pulumi_bitwarden",
  "classes": {
   "bitwarden:index/itemSecureNote:ItemSecureNote": "ItemSecureNote"
  }
 },
 {
  "pkg": "bitwarden",
  "mod": "index/itemSshKey",
  "fqn": "pulumi_bitwarden",
  "classes": {
   "bitwarden:index/itemSshKey:ItemSshKey": "ItemSshKey"
  }
 },
 {
  "pkg": "bitwarden",
  "mod": "index/orgCollection",
  "fqn": "pulumi_bitwarden",
  "classes": {
   "bitwarden:index/orgCollection:OrgCollection": "OrgCollection"
  }
 },
 {
  "pkg": "bitwarden",
  "mod": "index/project",
  "fqn": "pulumi_bitwarden",
  "classes": {
   "bitwarden:index/project:Project": "Project"
  }
 },
 {
  "pkg": "bitwarden",
  "mod": "index/secret",
  "fqn": "pulumi_bitwarden",
  "classes": {
   "bitwarden:index/secret:Secret": "Secret"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "bitwarden",
  "token": "pulumi:providers:bitwarden",
  "fqn": "pulumi_bitwarden",
  "class": "Provider"
 }
]
"""
)
