# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import sys

import pulumi
import pulumi.runtime

if sys.version_info >= (3, 11):
    pass
else:
    pass
from . import _utilities

__all__ = [
    'GetFolderResult',
    'AwaitableGetFolderResult',
    'get_folder',
    'get_folder_output',
]

@pulumi.output_type
class GetFolderResult:
    """
    A collection of values returned by getFolder.
    """
    def __init__(__self__, filter_collection_id=None, filter_organization_id=None, id=None, name=None, search=None):
        if filter_collection_id and not isinstance(filter_collection_id, str):
            raise TypeError("Expected argument 'filter_collection_id' to be a str")
        pulumi.set(__self__, "filter_collection_id", filter_collection_id)
        if filter_organization_id and not isinstance(filter_organization_id, str):
            raise TypeError("Expected argument 'filter_organization_id' to be a str")
        pulumi.set(__self__, "filter_organization_id", filter_organization_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if search and not isinstance(search, str):
            raise TypeError("Expected argument 'search' to be a str")
        pulumi.set(__self__, "search", search)

    @_builtins.property
    @pulumi.getter(name="filterCollectionId")
    def filter_collection_id(self) -> _builtins.str | None:
        return pulumi.get(self, "filter_collection_id")

    @_builtins.property
    @pulumi.getter(name="filterOrganizationId")
    def filter_organization_id(self) -> _builtins.str | None:
        return pulumi.get(self, "filter_organization_id")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str | None:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def search(self) -> _builtins.str | None:
        return pulumi.get(self, "search")


class AwaitableGetFolderResult(GetFolderResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetFolderResult(
            filter_collection_id=self.filter_collection_id,
            filter_organization_id=self.filter_organization_id,
            id=self.id,
            name=self.name,
            search=self.search)


def get_folder(filter_collection_id: _builtins.str | None = None,
               filter_organization_id: _builtins.str | None = None,
               id: _builtins.str | None = None,
               search: _builtins.str | None = None,
               opts: pulumi.InvokeOptions | None = None) -> AwaitableGetFolderResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['filterCollectionId'] = filter_collection_id
    __args__['filterOrganizationId'] = filter_organization_id
    __args__['id'] = id
    __args__['search'] = search
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('bitwarden:index/getFolder:getFolder', __args__, opts=opts, typ=GetFolderResult, package_ref=_utilities.get_package()).value

    return AwaitableGetFolderResult(
        filter_collection_id=pulumi.get(__ret__, 'filter_collection_id'),
        filter_organization_id=pulumi.get(__ret__, 'filter_organization_id'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        search=pulumi.get(__ret__, 'search'))
def get_folder_output(filter_collection_id: pulumi.Input[_builtins.str | None] | None = None,
                      filter_organization_id: pulumi.Input[_builtins.str | None] | None = None,
                      id: pulumi.Input[_builtins.str | None] | None = None,
                      search: pulumi.Input[_builtins.str | None] | None = None,
                      opts: pulumi.InvokeOptions | pulumi.InvokeOutputOptions | None = None) -> pulumi.Output[GetFolderResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['filterCollectionId'] = filter_collection_id
    __args__['filterOrganizationId'] = filter_organization_id
    __args__['id'] = id
    __args__['search'] = search
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('bitwarden:index/getFolder:getFolder', __args__, opts=opts, typ=GetFolderResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetFolderResult(
        filter_collection_id=pulumi.get(__response__, 'filter_collection_id'),
        filter_organization_id=pulumi.get(__response__, 'filter_organization_id'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        search=pulumi.get(__response__, 'search')))
