# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import sys
from typing import overload

import pulumi
import pulumi.runtime

if sys.version_info >= (3, 11):
    pass
else:
    pass
from . import _utilities

__all__ = ['SecretArgs', 'Secret']

@pulumi.input_type
class SecretArgs:
    def __init__(__self__, *,
                 key: pulumi.Input[_builtins.str],
                 note: pulumi.Input[_builtins.str],
                 project_id: pulumi.Input[_builtins.str],
                 value: pulumi.Input[_builtins.str],
                 organization_id: pulumi.Input[_builtins.str] | None = None,
                 secret_id: pulumi.Input[_builtins.str] | None = None):
        """
        The set of arguments for constructing a Secret resource.
        :param pulumi.Input[_builtins.str] key: Name.
        :param pulumi.Input[_builtins.str] note: Note.
        :param pulumi.Input[_builtins.str] project_id: Identifier of the project.
        :param pulumi.Input[_builtins.str] value: Value.
        :param pulumi.Input[_builtins.str] organization_id: Identifier of the organization.
        :param pulumi.Input[_builtins.str] secret_id: Identifier.
        """
        pulumi.set(__self__, "key", key)
        pulumi.set(__self__, "note", note)
        pulumi.set(__self__, "project_id", project_id)
        pulumi.set(__self__, "value", value)
        if organization_id is not None:
            pulumi.set(__self__, "organization_id", organization_id)
        if secret_id is not None:
            pulumi.set(__self__, "secret_id", secret_id)

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Input[_builtins.str]:
        """
        Name.
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter
    def note(self) -> pulumi.Input[_builtins.str]:
        """
        Note.
        """
        return pulumi.get(self, "note")

    @note.setter
    def note(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "note", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[_builtins.str]:
        """
        Identifier of the project.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter
    def value(self) -> pulumi.Input[_builtins.str]:
        """
        Value.
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "value", value)

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Input[_builtins.str] | None:
        """
        Identifier of the organization.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: pulumi.Input[_builtins.str] | None):
        pulumi.set(self, "organization_id", value)

    @_builtins.property
    @pulumi.getter(name="secretId")
    def secret_id(self) -> pulumi.Input[_builtins.str] | None:
        """
        Identifier.
        """
        return pulumi.get(self, "secret_id")

    @secret_id.setter
    def secret_id(self, value: pulumi.Input[_builtins.str] | None):
        pulumi.set(self, "secret_id", value)


@pulumi.input_type
class _SecretState:
    def __init__(__self__, *,
                 key: pulumi.Input[_builtins.str] | None = None,
                 note: pulumi.Input[_builtins.str] | None = None,
                 organization_id: pulumi.Input[_builtins.str] | None = None,
                 project_id: pulumi.Input[_builtins.str] | None = None,
                 secret_id: pulumi.Input[_builtins.str] | None = None,
                 value: pulumi.Input[_builtins.str] | None = None):
        """
        Input properties used for looking up and filtering Secret resources.
        :param pulumi.Input[_builtins.str] key: Name.
        :param pulumi.Input[_builtins.str] note: Note.
        :param pulumi.Input[_builtins.str] organization_id: Identifier of the organization.
        :param pulumi.Input[_builtins.str] project_id: Identifier of the project.
        :param pulumi.Input[_builtins.str] secret_id: Identifier.
        :param pulumi.Input[_builtins.str] value: Value.
        """
        if key is not None:
            pulumi.set(__self__, "key", key)
        if note is not None:
            pulumi.set(__self__, "note", note)
        if organization_id is not None:
            pulumi.set(__self__, "organization_id", organization_id)
        if project_id is not None:
            pulumi.set(__self__, "project_id", project_id)
        if secret_id is not None:
            pulumi.set(__self__, "secret_id", secret_id)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Input[_builtins.str] | None:
        """
        Name.
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: pulumi.Input[_builtins.str] | None):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter
    def note(self) -> pulumi.Input[_builtins.str] | None:
        """
        Note.
        """
        return pulumi.get(self, "note")

    @note.setter
    def note(self, value: pulumi.Input[_builtins.str] | None):
        pulumi.set(self, "note", value)

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Input[_builtins.str] | None:
        """
        Identifier of the organization.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: pulumi.Input[_builtins.str] | None):
        pulumi.set(self, "organization_id", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[_builtins.str] | None:
        """
        Identifier of the project.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[_builtins.str] | None):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter(name="secretId")
    def secret_id(self) -> pulumi.Input[_builtins.str] | None:
        """
        Identifier.
        """
        return pulumi.get(self, "secret_id")

    @secret_id.setter
    def secret_id(self, value: pulumi.Input[_builtins.str] | None):
        pulumi.set(self, "secret_id", value)

    @_builtins.property
    @pulumi.getter
    def value(self) -> pulumi.Input[_builtins.str] | None:
        """
        Value.
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: pulumi.Input[_builtins.str] | None):
        pulumi.set(self, "value", value)


@pulumi.type_token("bitwarden:index/secret:Secret")
class Secret(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: pulumi.ResourceOptions | None = None,
                 key: pulumi.Input[_builtins.str] | None = None,
                 note: pulumi.Input[_builtins.str] | None = None,
                 organization_id: pulumi.Input[_builtins.str] | None = None,
                 project_id: pulumi.Input[_builtins.str] | None = None,
                 secret_id: pulumi.Input[_builtins.str] | None = None,
                 value: pulumi.Input[_builtins.str] | None = None,
                 __props__=None):
        """
        Create a Secret resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] key: Name.
        :param pulumi.Input[_builtins.str] note: Note.
        :param pulumi.Input[_builtins.str] organization_id: Identifier of the organization.
        :param pulumi.Input[_builtins.str] project_id: Identifier of the project.
        :param pulumi.Input[_builtins.str] secret_id: Identifier.
        :param pulumi.Input[_builtins.str] value: Value.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: SecretArgs,
                 opts: pulumi.ResourceOptions | None = None):
        """
        Create a Secret resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param SecretArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SecretArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: pulumi.ResourceOptions | None = None,
                 key: pulumi.Input[_builtins.str] | None = None,
                 note: pulumi.Input[_builtins.str] | None = None,
                 organization_id: pulumi.Input[_builtins.str] | None = None,
                 project_id: pulumi.Input[_builtins.str] | None = None,
                 secret_id: pulumi.Input[_builtins.str] | None = None,
                 value: pulumi.Input[_builtins.str] | None = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SecretArgs.__new__(SecretArgs)

            if key is None and not opts.urn:
                raise TypeError("Missing required property 'key'")
            __props__.__dict__["key"] = key
            if note is None and not opts.urn:
                raise TypeError("Missing required property 'note'")
            __props__.__dict__["note"] = note
            __props__.__dict__["organization_id"] = organization_id
            if project_id is None and not opts.urn:
                raise TypeError("Missing required property 'project_id'")
            __props__.__dict__["project_id"] = project_id
            __props__.__dict__["secret_id"] = secret_id
            if value is None and not opts.urn:
                raise TypeError("Missing required property 'value'")
            __props__.__dict__["value"] = value
        super(Secret, __self__).__init__(
            'bitwarden:index/secret:Secret',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: pulumi.ResourceOptions | None = None,
            key: pulumi.Input[_builtins.str] | None = None,
            note: pulumi.Input[_builtins.str] | None = None,
            organization_id: pulumi.Input[_builtins.str] | None = None,
            project_id: pulumi.Input[_builtins.str] | None = None,
            secret_id: pulumi.Input[_builtins.str] | None = None,
            value: pulumi.Input[_builtins.str] | None = None) -> 'Secret':
        """
        Get an existing Secret resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] key: Name.
        :param pulumi.Input[_builtins.str] note: Note.
        :param pulumi.Input[_builtins.str] organization_id: Identifier of the organization.
        :param pulumi.Input[_builtins.str] project_id: Identifier of the project.
        :param pulumi.Input[_builtins.str] secret_id: Identifier.
        :param pulumi.Input[_builtins.str] value: Value.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SecretState.__new__(_SecretState)

        __props__.__dict__["key"] = key
        __props__.__dict__["note"] = note
        __props__.__dict__["organization_id"] = organization_id
        __props__.__dict__["project_id"] = project_id
        __props__.__dict__["secret_id"] = secret_id
        __props__.__dict__["value"] = value
        return Secret(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Output[_builtins.str]:
        """
        Name.
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter
    def note(self) -> pulumi.Output[_builtins.str]:
        """
        Note.
        """
        return pulumi.get(self, "note")

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Output[_builtins.str]:
        """
        Identifier of the organization.
        """
        return pulumi.get(self, "organization_id")

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Output[_builtins.str]:
        """
        Identifier of the project.
        """
        return pulumi.get(self, "project_id")

    @_builtins.property
    @pulumi.getter(name="secretId")
    def secret_id(self) -> pulumi.Output[_builtins.str]:
        """
        Identifier.
        """
        return pulumi.get(self, "secret_id")

    @_builtins.property
    @pulumi.getter
    def value(self) -> pulumi.Output[_builtins.str]:
        """
        Value.
        """
        return pulumi.get(self, "value")

